# Generated by Django 5.1.1 on 2024-09-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_added',
        ),
    ]
